export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVED_SELECTED_PRODUCT: "REMOVED_SELECTED_PRODUCT",

    SET_CART: "SET_CART",

    ADD_CART: "ADD_CART",
    DEL_CART: "DEL_CART",
    INC_CART: "INC_CART",
    DEC_CART: "DEC_CART",
}