export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVED_SELECTED_PRODUCT: "REMOVED_SELECTED_PRODUCT",
    ADD_CART: "ADD_CART",
    DEL_CART: "DEL_CART",
}